// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentLogLine = { id: bigint | null, host_id: string, ts: string, level: string, target: string, message: string, };
