// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentLogLine } from "./AgentLogLine";

export type AgentLogsResponse = { host_id: string, lines: Array<AgentLogLine>, };
