// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentLogLine } from "./AgentLogLine";
import type { ContainerSummary } from "./ContainerSummary";
import type { HelloPayload } from "./HelloPayload";
import type { LogLine } from "./LogLine";
import type { LogsResultData } from "./LogsResultData";
import type { TaskResultData } from "./TaskResultData";

export type AgentMsg = { "type": "Hello" } & HelloPayload | { "type": "Ping", containers: Array<ContainerSummary>, } | { "type": "TaskResult", task_id: string, result: TaskResultData, } | { "type": "LogsResult", task_id: string, result: LogsResultData, } | { "type": "LogChunk", subscription_id: string, workload_id: string, lines: Array<LogLine>, } | { "type": "LogStreamEnded", subscription_id: string, reason: string, } | { "type": "AgentLogs", batch: Array<AgentLogLine>, };
