// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiTokenSummary = { id: string, name: string, token_prefix: string, role: string, expires_at: string | null, last_used_at: string | null, created_at: string, 
/**
 * Only set once on create.
 */
token_once: string | null, };
