// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditWebhookSummary = { id: string, url: string, event_filter: Array<string>, failure_count: number, last_error: string | null, last_delivered_at: string | null, created_at: string, secret_once: string | null, };
