// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLogRow } from "./AuditLogRow";

export type AuditLogListResponse = { rows: Array<AuditLogRow>, next_cursor: bigint | null, count: number, };
