// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditLogRow = { id: bigint, ts: string, actor_user_id: string | null, actor_email: string | null, actor_tenant_id: string | null, action: string, resource_type: string | null, resource_id: string | null, result: string, ip_address: string | null, user_agent: string | null, details: string | null, };
