// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditVerifyResponse = { verified: boolean, last_verified_id: bigint | null, first_bad_id: bigint | null, };
