// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunContainerSpec } from "./RunContainerSpec";
import type { VolumeProvisionSpec } from "./VolumeProvisionSpec";

export type Command = { "kind": "RunContainer" } & RunContainerSpec | { "kind": "StopContainer", name: string, timeout_s: number, } | { "kind": "RemoveContainer", name: string, force: boolean, } | { "kind": "CreateVolume" } & VolumeProvisionSpec | { "kind": "DeleteVolume" } & VolumeProvisionSpec | { "kind": "FetchContainerLogs", workload_id: string, name: string, tail_lines: number, } | { "kind": "StreamContainerLogs", workload_id: string, name: string, subscription_id: string, } | { "kind": "CancelLogStream", subscription_id: string, } | { "kind": "Ping" };
