// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlPlaneLogLine } from "./ControlPlaneLogLine";

export type ControlPlaneLogsResponse = { lines: Array<ControlPlaneLogLine>, capacity: number, };
