// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateVolumeRequest = { host_id: string, name: string, 
/**
 * JSON number (fits JS safely for homelab sizes).
 */
size_mb: number, backend: string, };
