// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateApiTokenRequest = { name: string, 
/**
 * Optional role override (defaults to caller's tenant role, capped at operator for safety).
 */
role: string | null, expires_days: number | null, };
