// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortMapping } from "./PortMapping";
import type { VolumeAttachment } from "./VolumeAttachment";

export type CreateWorkloadRequest = { 
/**
 * Optional; when empty, control plane places on best online host.
 */
host_id: string | null, name: string, image: string, env: Array<[string, string]>, ports: Array<PortMapping>, volumes: Array<VolumeAttachment>, command: Array<string> | null, labels: Array<[string, string]>, 
/**
 * Host label selector: host must have all of these labels.
 */
placement_labels: Array<[string, string]>, };
