// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnrollTokenResponse = { token: string, install_command: string, expires_at: string, };
