// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnrollRequest = { enrollment_token: string, name: string, os: string, arch: string, agent_version: string, };
