// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerSummary } from "./ContainerSummary";

export type HelloPayload = { os: string, arch: string, agent_version: string, containers: Array<ContainerSummary>, };
