// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostSummary = { id: string, name: string, status: string, os: string | null, arch: string | null, agent_version: string | null, last_seen_at: string | null, created_at: string, labels: Array<[string, string]>, cordoned: boolean, };
