// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginRequest = { email: string, password: string, 
/**
 * TOTP code when MFA is enabled for the user.
 */
totp_code: string | null, };
