// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLine } from "./LogLine";

export type LogsResultData = { success: boolean, message: string | null, lines: Array<LogLine>, truncated: boolean, };
