// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MfaSetupResponse = { secret: string, otpauth_url: string, recovery_codes: Array<string>, };
