// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MountSpec = { host_path: string, container_path: string, read_only: boolean, };
