// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortMapping = { host_port: number, container_port: number, protocol: string, };
