// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountSpec } from "./MountSpec";
import type { PortMapping } from "./PortMapping";

export type RunContainerSpec = { workload_id: string, name: string, image: string, env: Array<[string, string]>, ports: Array<PortMapping>, mounts: Array<MountSpec>, command: Array<string> | null, };
