// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Command } from "./Command";

export type ServerMsg = { "type": "Pong" } | { "type": "Command", task_id: string, command: Command, };
