// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenantInfo } from "./TenantInfo";
import type { UserInfo } from "./UserInfo";

export type SessionInfo = { authenticated: boolean, setup_required: boolean, user: UserInfo | null, active_tenant: TenantInfo | null, mfa_enabled: boolean, mfa_required: boolean, };
