// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskResultData = { success: boolean, message: string | null, container_id: string | null, host_path: string | null, };
