// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenantInvitationSummary = { id: string, email: string, role: string, expires_at: string, created_at: string, invite_url: string | null, };
