// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TenantMemberSummary = { user_id: string, email: string, name: string, role: string, created_at: string, };
