// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeAttachment = { volume_id: string, mount_path: string, read_only: boolean, };
