// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeProvisionSpec = { volume_id: string, size_mb: number, backend: string, };
