// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkloadSummary = { id: string, name: string, host_id: string, host_name: string, image: string, desired_state: string, observed_state: string, container_id: string | null, last_error: string | null, created_at: string, labels: Array<[string, string]>, };
